version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/python-test
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /install-dependencies
      runas: root
  AfterInstall:
    - location: /after-install
      runas: root
