version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python-app
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /install-dependencies
      runas: root
  AfterInstall:
    - location: /after-install
      runas: root
