#!/bin/bash
sudo systemctl stop myapp.service
sudo apt install -y python3-pip
pip3 install -r /home/ubuntu/python-test/requirements.txt
sudo systemctl start myapp.service
sudo systemctl status myapp.service


